Check whether polytopes are reflexive

In [1]:
#!sudo apt update && sudo apt full-upgrade
#!sudo do-release-upgrade
#!sudo apt install python3-pip

!apt install libppl-dev
!apt install libmpfr-dev
!apt install libmpc-dev
!apt install libflint-dev
!apt install palp
!apt install libcgal-dev

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libgmp-dev libgmpxx4ldbl libppl-c4 libppl14
Suggested packages:
  gmp-doc libgmp10-doc libmpfr-dev libppl-doc
The following NEW packages will be installed:
  libgmp-dev libgmpxx4ldbl libppl-c4 libppl-dev libppl14
0 upgraded, 5 newly installed, 0 to remove and 49 not upgraded.
Need to get 3,874 kB of archives.
After this operation, 29.7 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgmpxx4ldbl amd64 2:6.2.1+dfsg-3ubuntu1 [9,580 B]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgmp-dev amd64 2:6.2.1+dfsg-3ubuntu1 [337 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libppl14 amd64 1:1.2-8.1build1 [434 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libppl-c4 amd64 1:1.2-8.1build1 [1,084 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe

In [2]:
!cd /usr/local/lib/python3.10/dist-packages/cytools
!ls -la /usr/local/lib/python3.10/dist-packages/cytools

/bin/bash: line 1: cd: /usr/local/lib/python3.10/dist-packages/cytools: No such file or directory
ls: cannot access '/usr/local/lib/python3.10/dist-packages/cytools': No such file or directory


In [3]:
!python3 --version

Python 3.10.12


In [4]:
!pip install gmpy2 sympy tqdm python-flint ortools pandas qpsolvers
!pip install cysignals
!pip install pplpy
!pip install scipy
!pip install Mosek
!pip install cytools

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 20.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.1/41.1 MB 20.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.1/28.1 MB 38.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.2/82.2 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.8/302.8 kB 16.3 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
  Attempting uninstall: absl-py
    Found existing installation: absl-py 1.4.0
    Uninstalling absl-py-1.4.0:
      Successfully uninstalled absl-py-1.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-datastore 2.19.0 re

In [5]:
from cytools import Polytope
import cytools
cytools.config.enable_experimental_features()

/usr/local/lib/python3.10/dist-packages/cytools/config.py:139: UserWarning: 
**************************************************************
Some of these features may be broken or not fully tested,
and they may undergo significant changes in future versions.
**************************************************************

  warnings.warn("\n**************************************************************\n"


In [ ]:
# check some fundamental features
vertices = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1],[-1,-1,-6,-9]]
p = Polytope(vertices)
print(p.faces(d=2)[0].points())

First check all 16 two dimensional polytopes

In [17]:
print(Polytope([[-1,2],[2,-1],[-1,-1]]).is_reflexive())
print(Polytope([[0,1],[1,0],[-1,-1]]).is_reflexive())

print(Polytope([[0,1],[2,-1],[-2,-1]]).is_reflexive())
print(Polytope([[0,1],[1,-1],[-1,-1]]).is_reflexive())

print(Polytope([[-1,1],[1,1],[1,-1],[-1,-1]]).is_reflexive())
print(Polytope([[0,1],[1,0],[0,-1],[-1,0]]).is_reflexive())

print(Polytope([[0,1],[1,0],[1,-1],[-1,-1],[-1,1]]).is_reflexive())
print(Polytope([[0,1],[1,0],[0,-1],[-1,-1],[-1,0]]).is_reflexive())

print(Polytope([[0,1],[2,-1],[-1,-1],[-1,1]]).is_reflexive())
print(Polytope([[0,1],[1,0],[0,-1],[-1,-1]]).is_reflexive())

print(Polytope([[0,1],[2,-1],[-1,-1],[-1,0]]).is_reflexive())
print(Polytope([[0,1],[1,0],[1,-1],[-1,-1]]).is_reflexive())

print(Polytope([[0,1],[2,-1],[-1,-1]]).is_reflexive())
print(Polytope([[0,1],[1,-1],[-1,-1],[-1,1]]).is_reflexive())

print(Polytope([[0,1],[1,0],[1,-1],[-1,-1],[-1,0]]).is_reflexive())
print(Polytope([[0,1],[1,0],[1,-1],[0,-1],[-1,0],[1,1]]).is_reflexive())

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [ ]:
p = Polytope([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[-1,-1,-6,-9,0],[0,0,0,0,1],[0,0,0,0,-1]])


/usr/local/lib/python3.10/dist-packages/cytools/config.py:139: UserWarning: 
**************************************************************
Some of these features may be broken or not fully tested,
and they may undergo significant changes in future versions.
**************************************************************

  warnings.warn("\n**************************************************************\n"


In [ ]:
vertices = [[ -1,   0,   1,   1,   3],
  [  3,   4,  -3,   9,  -5],
  [ -1,  -8,   1, -15,   3],
  [  0,   0,   1,   1,   0],
  [ -1,   0,  -3,   1,  -1],
  [ -1,   0,   1,  -7,   3]]
p = Polytope(vertices)
print(p.is_reflexive())

True


Take some 5D polytopes from [GitHub: elliheyes/Polytope-Generation](https://github.com/elliheyes/Polytope-Generation/tree/main/Data)

In [ ]:
vertices = [[-2, 3, 1, -3, 0],
 [1, -2, -1, 2, 0],
 [4, -4, 1, 2, -2],
 [1, 2, 3, 0, -1],
 [-3, 3, -1, -2, 2],
 [1, 2, 3, -3, -1],
 [-2, -1, -3, 0, 2]]
p = Polytope(vertices)
print(p.is_reflexive())

vertices = [[4, -2, 3, 2, -3],
 [1, -2, -1, 2, 0],
 [4, -4, 1, 2, -2],
 [1, 2, 3, 0, -1],
 [-3, 3, -1, -2, 2],
 [1, 2, 3, -3, -1],
 [-2, -4, -5, 2, 1]]
p = Polytope(vertices)
print(p.is_reflexive())

True
True


In [ ]:
vertices = [[ -2,   0,   0,   1,  -1],
 [  1,   0,   0,  -2,  -2],
 [  0,   0,   0,   1,   1],
 [ -2,  -1,   0,  -2,  -1],
 [ -3,   2,  -1,   5,  -2],
 [  1,   0,   0,  -1,   0],
 [  0,  -1,   1,   1,   3],
 [  6,  -1,   1,  -5,   1],
 [-12,   2,  -2,   7,  -7]]
p = Polytope(vertices)
print(p.is_reflexive())
print(p.hpq(1,1,lattice="N"))
print(p.hpq(1,2,lattice="N"))
print(p.hpq(1,3,lattice="N"))
print(p.hpq(2,2,lattice="N"))
print(p.chi(lattice="N"))

vertices = [[  0,   0,   0,   1,   1],
 [  1,   0,   0,  -2,  -2],
 [  0,   0,   0,   1,   1],
 [  0,  -2,   0,   1,  -1],
 [ -5,   3,  -1,   1,  -4],
 [  1,   0,   0,  -1,   0],
 [  0,  -1,   1,   1,   3],
 [  6,  -1,   1,  -5,   1],
 [-12,   2,  -2,   7,  -7]]
p = Polytope(vertices)
print(p.is_reflexive())
print(p.hpq(1,1,lattice="N"))
print(p.hpq(1,2,lattice="N"))
print(p.hpq(1,3,lattice="N"))
print(p.hpq(2,2,lattice="N"))
print(p.chi(lattice="N"))

True
9
2
305
1296
1920
True
11
0
301
1292
1920


In [ ]:
vertices = [[-4, 3, 1, -3, 2],
 [1, 4, -4, -2, -3],
 [-1,  0,  2, -2,  1],
 [ 4,  0, -3, -2, -4],
 [ 2, -1,  0, -2,  1],
 [-1,  2,  0, -2,  1],
 [ 3, -3,  4,  1, -2]]
p = Polytope(vertices)
print(p.is_reflexive())

False


Check extremal cases

In [ ]:
vertices = [[  0,  -1,   1,  -1,  -5],
  [  0,   2,  -2,   1, -69],
  [  0,   1,   0,  -1,  -4],
  [ -3,   0,   2,  -7,   0],
  [ -1,  -1,   1,  -2,   0],
  [  3,  -2,   1,   5,  141]]
p = Polytope(vertices)
print(p.is_reflexive())

vertices = [[     0,     -1,      1,     -1,     -5],
       [     0,      2,     -2,      1, -99999],
       [     0,      1,      0,     -1,     -4],
       [    -3,      0,      2,     -7,      0],
       [    -1,     -1,      1,     -2,      0],
       [     3,     -2,      1,      5, 200001]]
p = Polytope(vertices)
print(p.is_reflexive())



True
True


In [ ]:
from scipy.spatial import ConvexHull
from scipy.spatial.distance import cdist
import numpy as np

vertices = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1],[-1,-2,-1,-1],[-2,-1,-1,-1]]
vertices = np.array(vertices)

hull = ConvexHull(vertices)
hull_simplices = hull.simplices
print("4-dimensional simplices from convex hull:", hull_simplices)

# Extend each 4-simplex into a 5-simplex by adding an origin vertex (assuming index '6')
origin_vertex = np.zeros((1, vertices.shape[1]))
all_vertices = np.vstack([vertices, origin_vertex])

# Convert each 4D simplex to 5D by adding the origin (index 6)
extended_hull_simplices = [[6] + list(simplex) for simplex in hull_simplices]
print("5-dimensional cones for CYTools:", extended_hull_simplices)

cytools_simplices = [[0,1,2,3,4],[0,1,2,3,5],[0,1,2,4,6],[0,1,2,5,6],[0,1,3,4,5],[0,1,4,5,6],[0,2,3,4,5],[0,2,4,5,6]]

# Convert each simplex in both lists to a set of vertices
hull_simplices_sets = [set(simplex) for simplex in extended_hull_simplices]
cytools_simplices_sets = [set(simplex) for simplex in cytools_simplices]

# Convert the lists of sets to sets of sets for order-insensitive comparison
hull_simplices_set_of_sets = set(map(frozenset, hull_simplices_sets))
cytools_simplices_set_of_sets = set(map(frozenset, cytools_simplices_sets))

# Check if both sets are equal
print("The simplices are equivalent:", hull_simplices_set_of_sets == cytools_simplices_set_of_sets)

p = Polytope(vertices)
#p.triangulate(simplices=extended_hull_simplices)

4-dimensional simplices from convex hull: [[3 2 4 5]
 [3 2 4 0]
 [1 3 2 5]
 [1 3 2 0]
 [1 2 4 0]
 [1 2 4 5]
 [1 3 4 5]
 [1 3 4 0]]
5-dimensional cones for CYTools: [[6, 3, 2, 4, 5], [6, 3, 2, 4, 0], [6, 1, 3, 2, 5], [6, 1, 3, 2, 0], [6, 1, 2, 4, 0], [6, 1, 2, 4, 5], [6, 1, 3, 4, 5], [6, 1, 3, 4, 0]]
The simplices are equivalent: False


In [ ]:
from scipy.spatial import ConvexHull
import numpy as np
vertices = [[-2,3,1,-3,0], [1,-2,-1,2,0], [4,-4,1,2,-2], [1,2,3,0,-1], [-3,3,-1,-2,2], [1,2,3,-3,-1], [-2,-1,-3,0,2]]
hull = ConvexHull(vertices)

print(hull.simplices)
p = Polytope(vertices)
print(p.is_reflexive())

nef_part = p.nef_partitions(compute_hodge_numbers=False)
t = p.triangulate(simplices=hull.simplices, include_points_interior_to_facets=True)
cy = t.get_cy(nef_part[0])
cy.h11() # The function is called here since the Hodge numbers have not been computed
# 4
cy.h21() # It is not called here because the Hodge numbers are already cached
# 544


[[1 3 0 6 4]
 [1 3 0 6 2]
 [5 3 0 6 4]
 [5 3 0 6 2]
 [5 1 3 0 4]
 [5 1 3 0 2]
 [5 1 0 6 2]
 [5 1 0 6 4]
 [5 1 3 6 4]
 [5 1 3 6 2]]
True


ValueError: Input simplices have wrong dimension.